#!/bin/bash

export UE4_VERSION=${SOURCE_BRANCH}
export UBUNTU_VERSION="20.04"

# Android SDK Versions (see ue4-android-sdk)
export OPENJDK_VERSION="8"
export NDK_VERSION="21.1.6352462"
export BUILD_TOOLS_VERSION="30.0.1"

# build image
docker build \
--tag ${IMAGE_NAME} \
--build-arg UE4_VERSION=${UE4_VERSION} \
--build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
--build-arg OPENJDK_VERSION=${OPENJDK_VERSION} \
--build-arg NDK_VERSION=${NDK_VERSION} \
--build-arg BUILD_TOOLS_VERSION=${BUILD_TOOLS_VERSION} \
--no-cache \
-f ./${DOCKERFILE_PATH} \
.
